version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
      - ./.mongodb:/data/db
    ports:
      - 27017:27017

  mongodb-test:
    image: mongo
    container_name: 'mongodb-test'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27017